spring:
  profiles:
    active: dev

server:
  port: 8080

logging:
  level:
    root: INFO
    com.company.customersearch: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %mdc %-5level %logger{36} - %msg%n'

external:
  api:
    base-url: http://localhost:3000
